events/urls.py
from django.urls import re_path
from django.views.generic.detail import DetailView

from .models import Event
from .views import (EventDetail,
                    EventList,
                    EventCreate,
                    EventUpdate,
                    EventDelete,
                    EventsFeed,
                    EventParticipationList,
                    EventParticipationCreate,
                    EventParticipationDetail,
                    EventParticipationDelete,
                    EventParticipationDownload)

urlpatterns = [
    re_path(r'^$', EventList.as_view(), name='events_list_all'),
    re_path(r'^rss$', EventsFeed(), name='events_feed'),
    re_path(r'^(?P<pk>\d+)/$', EventDetail.as_view(), name='detail'),
    re_path(r'^add/$', EventCreate.as_view(), name='add'),
    re_path(r'^(?P<pk>\d+)/editar/$', EventUpdate.as_view(), name='edit'),
    re_path(r'^(?P<pk>\d+)/borrar/$', EventDelete.as_view(), name='delete'),
    re_path(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(model=Event), name='event_slug'),

    # Event Registration Management
    re_path(r'^(?P<pk>\d+)/inscribirse/$', EventParticipationCreate.as_view(), name='register'),
    re_path(r'^(?P<pk>\d+)/inscriptos/$', EventParticipationList.as_view(), name='registered'),
    re_path(r'^(?P<pk>\d+)/inscriptos/csv/$', EventParticipationDownload.as_view(),
            name='registered_csv'),
    re_path(r'^(?P<pk>\d+)/inscripcion/(?P<participation_pk>\d+)/$',
            EventParticipationDetail.as_view(),
            name='registration'),
    re_path(r'^(?P<pk>\d+)/inscripcion/(?P<participation_pk>\d+)/borrar/$',
            EventParticipationDelete.as_view(), name='unregister'),
]

jobs/urls.py
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.urls import re_path
from .models import Job
from .views import (JobCreate, JobList, JobDelete, JobUpdate, JobsFeed,
                    JobInactivate)


urlpatterns = [
    re_path(r'^$', JobList.as_view(), name='jobs_list_all'),
    re_path(r'^rss$', JobsFeed(), name='jobs_feed'),
    re_path(r'^add/$', login_required(JobCreate.as_view()), name='jobs_add'),
    re_path(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(model=Job), name='jobs_view'),
    re_path(r'^(?P<pk>\d+)/delete/$', login_required(JobDelete.as_view()), name='jobs_delete'),
    re_path(r'^(?P<pk>\d+)/update/$', login_required(JobUpdate.as_view()), name='jobs_update'),
    re_path(r'^(?P<pk>\d+)/inactivate/$', login_required(JobInactivate.as_view()),
            name='jobs_inactivate'),
]

pyarweb/urls.py
# -*- coding: utf-8 -*-


"""URLS configurations for PyAr Web."""
import re

from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import re_path
from django.views.static import serve

from .views import buscador, irc

from community.views import homepage

admin.autodiscover()

app_name = 'pyarweb'
urlpatterns = [
    re_path(r'^irc/$', irc, name='irc'),
    re_path(r'^buscador/$', buscador, name='buscador'),

    re_path(r'^$', homepage, name='homepage'),

    re_path(r'^noticias/', include('news.urls')),
    re_path(r'^empresas/', include(('pycompanies.urls', 'pycompanies'), namespace='companies')),
    re_path(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    re_path(r'^summernote/', include('django_summernote.urls')),
    re_path(r'^trabajo/', include('jobs.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include('allauth.urls')),
    re_path(r'^eventos/', include(('events.urls', 'events'), namespace='events')),
    re_path(r'^planeta/', include('planet.urls')),
    re_path(r'^captcha/', include('captcha.urls')),
    re_path(r'^email_confirmation/', include(('email_confirm_la.urls', 'email_confirm_la.urls'),
                                             namespace='email_confirm_la')),

    # no puedo usar el static porque no funcia en produccion y en prod django esta
    # sirviendo los archivos estaticos. Esto es sacado del codigo de la funcion.
    # si es un HACK, pero hasta que pueda solucionarlo usando django-assets o algo asi
    re_path(
        r'^%s(?P<path>.*)$' % re.escape(settings.STATIC_URL.lstrip('/')),
        serve,
        kwargs=dict(document_root=settings.STATIC_ROOT)
    ),
    re_path(
        r'^%s(?P<path>.*)$' % re.escape(settings.MEDIA_URL.lstrip('/')),
        serve,
        kwargs=dict(document_root=settings.MEDIA_ROOT)
    ),
]

events/views.py
from braces.views import LoginRequiredMixin
from community.views import validate_obj_owner, OwnedObject
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.syndication.views import Feed
from django.http import Http404, HttpResponseRedirect
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import (CreateView,
                                       UpdateView,
                                       DeleteView)

from .forms import EventForm, AnonymousEventParticipationForm, AuthenticatedEventParticipationForm
from .models import Event, EventParticipation
from .mixins import EventMixin, EventParticipationMixin, CSVResponseMixin


class EventsFeed(Feed):
    title = "Feed de Próximos Eventos de PyAr"
    link = reverse_lazy("events:events_list_all")
    description = "Eventos de Python Argentina y relacionados"
    description_template = "events/event_detail_body.html"

    def items(self):
        return Event.objects.filter(end_at__gte=timezone.now()).order_by('-updated_at')[:10]

    def item_title(self, item):
        return item.name

    def item_pubdate(self, item):
        return item.created_at

    def item_updateddate(self, item):
        return item.updated_at

    def author_name(self, item):
        if item:
            return str(item.owner)
        return ''


class EventList(ListView):
    queryset = Event.objects.filter(
        end_at__lt=timezone.now()).order_by('-start_at')
    paginate_by = 5
    context_object_name = "eventos_pasados"

    def get_context_data(self, **kwargs):
        context = super(EventList, self).get_context_data(**kwargs)
        context['eventos_proximos'] = Event.objects.filter(
            end_at__gte=timezone.now()).order_by('start_at')

        return context


class EventDetail(EventMixin, DetailView):
    context_object_name = "event"

    def user_participation_details(self):
        """ Collect the necessary info for the template context if the user is already registered
        to the Event.
        :return: dict with 'user_is_registered' (bool) and  'participation_id' (int | None) fields

        """
        details = {
            'user_is_registered': False,
            'participation_id': None
        }
        user = self.request.user
        if user.is_anonymous:
            return details

        try:
            participation = self.object.participants.get(user=user)
            details.update(user_is_registered=True, participation_id=participation.id)
        except EventParticipation.DoesNotExist:
            pass
        return details

    def get_context_data(self, **kwargs):
        context = super(EventDetail, self).get_context_data(**kwargs)
        context.update(self.user_participation_details())
        return context


class EventCreate(LoginRequiredMixin, EventMixin, CreateView):
    form_class = EventForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(EventCreate, self).form_valid(form)


class EventUpdate(LoginRequiredMixin, EventMixin, OwnedObject, UpdateView):
    form_class = EventForm


class EventDelete(LoginRequiredMixin, OwnedObject, DeleteView):
    model = Event
    success_url = reverse_lazy("events:events_list_all")


class EventParticipationCreate(SuccessMessageMixin, EventParticipationMixin, CreateView):
    form_class = AnonymousEventParticipationForm

    def aux_get_user_name(self):
        user = self.request.user
        return user.get_full_name() or user.get_username()

    def form_valid(self, form):
        # Set the EventParticipation event from the URL param.
        event_id = self.kwargs['pk']
        form.instance.event_id = event_id

        if self.request.user.is_authenticated():
            response = self.form_valid_for_authenticated_user(form)
        else:
            response = self.form_valid_for_anonymous_user(form)

        return response

    def get(self, request, *args, **kwargs):
        """
        Handles GET requests and instantiates a blank version of the form.
        """
        if self.request.user.is_authenticated():
            event = self.get_event()
            participation = event.participants.filter(user_id=self.request.user.id)
            if participation.exists():
                return HttpResponseRedirect(
                    reverse_lazy('events:registration',
                                 kwargs={
                                     'pk': event.id,
                                     'participation_pk': participation.get().is_authenticated
                                 }
                                 )
                )
        return super().get(request, *args, **kwargs)

    def get_form_class(self):
        """
        Returns the form class to use in this view
        """
        self.form_class = AnonymousEventParticipationForm
        if self.request.user.is_authenticated():
            self.form_class = AuthenticatedEventParticipationForm
        return self.form_class

    def get_initial(self):
        """
        Returns the initial data to use for forms on this view.
        """
        initial = super().get_initial()
        initial['event'] = self.get_event()
        user = self.request.user
        if user.is_authenticated():
            initial['name'] = self.aux_get_user_name()
            initial['email'] = user.email
        return initial

    def get_success_message(self, cleaned_data):
        success_message = "Tu inscripción al evento ha sido registrada."
        if not self.request.user.is_authenticated():
            success_message = "Recibirás un email para confirmar la dirección provista y así " \
                              "completar tu inscripción."
        return _(success_message + '<br><i>¡Muchas gracias!</i>')

    def form_valid_for_authenticated_user(self, form):
        form.instance.user = self.request.user
        form.instance.name = self.aux_get_user_name()
        form.instance.email = self.request.user.email

        return super().form_valid(form)

    def form_valid_for_anonymous_user(self, form):
        if EventParticipation.objects.filter(email=form.instance.email).exists():
            # If the email is already registered, silently redirect to the success URL.
            # This is to avoid any information leaking.
            return HttpResponseRedirect(self.get_success_url())
        return super().form_valid(form)


class EventParticipationDetail(LoginRequiredMixin, SuccessMessageMixin, EventParticipationMixin,
                               UpdateView):
    pk_url_kwarg = 'participation_pk'
    success_message = _("Tu inscripción al evento ha sido actualizada.")

    def get_form_class(self):
        """
        Returns the form class to use in this view
        """
        self.form_class = AnonymousEventParticipationForm
        if self.request.user.is_authenticated():
            self.form_class = AuthenticatedEventParticipationForm
        return self.form_class

    def get_initial(self):
        """
        Returns the initial data to use for forms on this view.
        """
        initial = super().get_initial()
        initial['event'] = self.get_event()
        return initial

    def get_success_url(self):
        return self.object.event.get_absolute_url()


class EventParticipationList(LoginRequiredMixin, ListView):
    http_method_names = [u'get']
    context_object_name = 'participants'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__event = None

    def get_context_data(self, **kwargs):
        """Overwrite get_context_data to add the related Event's ID to the template context."""
        context = super(EventParticipationList, self).get_context_data(**kwargs)
        context['event'] = self.event
        return context

    @property
    def event(self):
        if self.__event is None:
            event = Event.objects.get(pk=self.kwargs['pk'])
            self.__event = validate_obj_owner(event, self.request.user)
        return self.__event

    def get_queryset(self):
        self.queryset = self.event.participants.all()
        return super().get_queryset()


class EventParticipationDelete(LoginRequiredMixin, EventParticipationMixin, DeleteView):
    pk_url_kwarg = 'participation_pk'

    def get_object(self, *args, **kwargs):
        """A User can delete its participation to an Event. The Event owner can also do that."""

        inscription = super(EventParticipationDelete, self).get_object(*args, **kwargs)
        if self.request.user not in [inscription.user, inscription.event.owner]:
            raise Http404()
        return inscription


class EventParticipationDownload(CSVResponseMixin, EventParticipationList):
    def get_csv_filename(self):
        event = self.event.name.lower().replace(' ', '_')
        timestamp = timezone.now().isoformat().replace(':', '').replace('-', '').split('.')[0]
        return '{0}-{1}.csv'.format(event, timestamp)

    def get_rows(self):
        columns = ('Nombre', 'Correo electrónico', 'Género', 'Nivel', 'Usuario PyAr',
                   'Verificado?')
        if self.event.has_sponsors:
            columns += ('CV', 'Comparte?')
        header = [columns]
        return header + list(map(self.participation_to_row, self.get_queryset()))

    def participation_to_row(self, obj):
        """Auxiliary method to convert an EventParticipation instance in a row for the CSV file."""
        user = ''
        if obj.user is not None:
            user = obj.user.get_full_name() or obj.user.get_username()
        row = (obj.name, obj.email, obj.gender, obj.seniority, user, obj.is_verified)
        if self.event.has_sponsors:
            row += (obj.cv, obj.share_with_sponsors)
        return row

templates/events/event_confirm_delete.html
{% extends "base.html" %}

{% load i18n %}

{% load devtags %}

{% block content %}

	<main id="main" class="container" role="main">
	    <div class="row">
	        <div class="col-md-12">
		        <form method="post">{% csrf_token %}
				    {% trans "Are you sure you want to delete" %} "{{ object.name }}" ?
				    <input type="submit" value="Yes" class="btn btn-danger">
				    <a href="{% url 'events:events_list_all' %}" class="btn btn-default">No</a>
				</form>
	        </div>
	    </div>
	</main>

{% endblock %}

templates/events/event_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load devtags %}
{% block title %}
    {{ event.name }}
{% endblock title %}
{% block stylesheets %}
    <link rel="stylesheet" href="/static/css/event_map.css">
{% endblock %}

{% block javascripts %}
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
{% endblock %}

{% block content %}
    <main id="main" class="container" role="main">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h1>

                        {{ event.name }}

                        <span class="section-button-group pull-right">
                          <a href="{% url 'events:events_list_all' %}" class="btn btn-info">
                              {% trans "Volver a eventos" %}
                          </a>
                          {% if event.owner == user %}
                              <a class="btn btn-default" href="{% url 'events:edit' event.id %}">
                                  {% trans 'Modificar' %}
                              </a>
                              <a class="btn btn-danger" href="{% url 'events:delete' event.id %}">
                                  {% trans 'Borrar' %}
                              </a>
                          {% endif %}
                        </span>
                    </h1>
                    <small>
                        {{ event.updated_at }} {% trans 'por' %} {{ event.owner }}
                    </small>
                </div>
            </div>
        </div>

        <div class="row">
            {% include "events/event_detail_body.html" with obj=event %}
        </div>

        <input type="hidden" id="id_lat" value="{{ event.lat }}">
        <input type="hidden" id="id_lng" value="{{ event.lng }}">
        <input type="hidden" id="id_zoom" value="{{ event.zoom }}">
    </main>
{% endblock %}

templates/events/event_detail_body.html
{% load i18n %}


<div class="col-md-6">

<h3>{% trans "¿De qué se trata?" %}</h3>
<p>{{ obj.description|safe }}</p>

</div>

<div class="col-md-6">

<h3>{% trans "¿Cuándo?" %}</h3>
{% if obj.start_at %}
  <p>{% trans "Comienza" %}: {{ obj.start_at }}</p>
{% endif %}

{% if obj.end_at %}
  <p>{% trans "Termina" %}: {{ obj.end_at }}</p>
{% endif %}

<h3>{% trans "¿Dónde?" %}</h3>
<p>{{ obj.place }} | {{ obj.address }}</p>


{% if obj.url %}
  <h3>{% trans "Más Información" %}</h3>
  <p>
    <a href="{{ obj.url }}">{{ obj.url }}</a>
  </p>
{% endif %}

{% if obj.registration_enabled %}
  <p>
    {% if user == event.owner %}
        <a class="btn btn-primary center" href="{% url 'events:registered' event.id %}">
          {% trans 'Ver inscriptos' %}
        </a>
    {% else %}
        {% if user_is_registered %}
            <a class="btn btn-primary center" href="{% url 'events:registration' event.id participation_id %}">
              {% trans 'Ver mi inscripción' %}
            </a>
        {% else %}
            {% if event %}
                <a class="btn btn-primary center" href="{% url 'events:register' event.id %}">
                  {% trans 'Inscribirme' %}
                </a>
            {% endif %}
        {% endif %}
    {% endif %}
  </p>
{% endif %}

templates/events/event_form.html
{% extends "base.html" %}

{% load i18n %}
{% load devtags %}
{% load crispy_forms_tags %}

{% block stylesheets %}
  <link rel="stylesheet" href="/static/css/event_map.css">
  {{ form.media.css }}
{% endblock %}

{% block title %}
    {% if form.instance.id %}
        {% trans 'Editar Evento' %}
    {% else %}
        {% trans 'Agregar Evento' %}
    {% endif %}
{% endblock %}

{% block content %}

  <main id="main" class="container" role="main">
    <div class="col-lg-12">
      <div class="page-header">
        <h2>
          {% if form.instance.id %}
            {% trans 'Editar Evento' %}
          {% else %}
            {% trans 'Agregar Evento' %}
          {% endif %}

          <span class="section-button-group pull-right">
                <a href="{% url 'events:events_list_all' %}" class="btn btn-info">
                  {% trans "Volver a eventos" %}
                </a>
            </span>
        </h2>
      </div>

      {% crispy form %}

    </div>
  </main>

{% endblock %}

{% block javascripts %}

  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  
  {{ form.media.js }}

{% endblock %}

templates/events/event_list.html
{% extends "base_site.html" %}

{% load i18n pagination_tags %}

{% load devtags %}

{% block title %}Eventos{% endblock %}

{% block left-column %}

  <!-- Proximos eventos -->

  <section>
    <div class="page-header">
      <h2>
        {% trans "Proximos Eventos" %}

        <span class="section-button-group pull-right">
          <a href="{% url 'events:add' %}" class="btn btn-info">{% trans "Agregar" %}</a>
        </span>

        <div class="pull-right">
                <a href="{% url 'events:events_feed' %}" class="badge">
                    <i class="fa fa-rss"></i> RSS
                </a>
           </div>


      </h2>


    </div>

    {% for event in eventos_proximos %}
      <article class="list-group-item">
        <h4 class="list-group-item-heading">
          <a href="{% url 'events:detail' event.id %}">
            {{ event.name }}
          </a> |
          <small>
            {{ event.start_at|date:"DATE_FORMAT" }} |
            {{ event.start_at|time:"TIME_FORMAT" }}
          </small>
        </h4>
        <p class="list-group-item-text">
          {{ event.description|truncatewords:"100"|striptags|safe }}
          <hr>
        </p>
      </article>
    {% empty %}
      <article class="list-group-item">
        <p class="list-group-item-text">{% trans "No hay eventos a futuro" %}</p>
      </article>
    {% endfor %}

    <hr>

    <header class="page-header">
        <h2>
          {% trans "Eventos pasados" %}
        </h2>
    </header>

    {% for event in eventos_pasados %}

      <article class="list-group-item">
        <h4 class="list-group-item-heading">
          <a href="{% url 'events:detail' event.id %}">
            {{ event.name }}
          </a> |
          <small>
            {{ event.start_at|date:"DATE_FORMAT" }} |
            {{ event.start_at|time:"TIME_FORMAT" }}
          </small>
        </h4>
        <p class="list-group-item-text">{{ event.description|striptags|truncatewords:"20" }}</p>
      </article>

    {% empty %}
      <article class="list-group-item">
        <p class="list-group-item-text">{% trans "No hay eventos pasados" %}</p>
      </article>
    {% endfor %}

    {% if eventos_pasados %}
        {% paginate %}
    {% endif %}

  </section>
{% endblock %}

templates/events/eventparticipation_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% load devtags %}
{% block content %}

	<main id="main" class="container" role="main">
	    <div class="row">
	        <div class="col-md-12">
		        <form method="post">{% csrf_token %}
                    <h4>
                        {% if user == object.user %}
                            {% trans "Seguro que quiere cancelar su inscripción al evento " %}
                        {% else %}
                            {% trans "Seguro que quiere cancelar la inscripción de" %}
                            "{{ object.name }}"<{{ object.email|urlize }}>
                            {% trans "al evento" %}
                        {% endif %}
                        <strong>"{{ object.event.name }}" </strong>?
                    </h4>

				    <input type="submit" value="Si" class="btn btn-danger">
				    <a href="{% url 'events:detail' object.event.id %}" class="btn btn-default">No</a>
				</form>
	        </div>
	    </div>
	</main>

{% endblock %}

templates/events/eventparticipation_form.html
{% extends "base.html" %}
{% load i18n %}
{% load devtags %}
{% load crispy_forms_tags %}
{% block stylesheets %}
    {{ form.media.css }}
{% endblock %}


{% block title %}
    {% if form.instance.id %}
        {% trans 'Editar participación' %}
    {% else %}
        {% trans 'Inscripción' %}
    {% endif %}
{% endblock %}


{% block content %}
    <main id="main" class="container" role="main">
        <div class="col-lg-12">
            {% if form.initial.event.registration_enabled %}
                <div class="page-header">
                    <small>
                        {{ form.initial.event.name }}
                    </small>
                    <h2>
                        {% if form.instance.id %}
                            {% trans 'Editar participación' %}
                        {% else %}
                            {% trans 'Participar' %}
                        {% endif %}

                        <span class="section-button-group pull-right">
                            <a href="{% url 'events:detail' form.initial.event.id %}" class="btn btn-info">
                                {% trans "Volver al evento" %}
                            </a>
                            {% if form.instance.id %}
                                <a href="{% url 'events:unregister' form.instance.event.id form.instance.id %}" class="btn btn-danger">
                                    {% trans "Eliminar" %}
                                </a>
                            {% endif %}
                        </span>
                    </h2>
                </div>

                {% crispy form %}

            </div>
        {% else %}
            <div class="page-header">
                <h2>
                    {% trans "Este evento no permite inscripción." %}
                    <span class="section-button-group pull-right">
                        <a href="{% url 'events:detail' form.initial.event.id %}" class="btn btn-info">
                            {% trans "Volver al evento" %}
                        </a>
                    </span>
                </h2>
            </div>
        {% endif %}
    </main>
{% endblock %}

{% block javascripts %}
    {{ form.media.js }}
{% endblock %}

templates/events/eventparticipation_list.html
{% extends "base_site.html" %}

{% load i18n pagination_tags %}

{% load devtags %}

{% block title %}Participantes{% endblock %}

{% block content %}
    <main id="main" class="container" role="main">
        <section>
            <div class="page-header">
                <h2>
                    {% trans "Participantes" %}
                    <span class="section-button-group pull-right">
                        <a href="{% url 'events:registered_csv' event.id %}" class="btn btn-default">
                            <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                            {% trans "Bajar CSV" %}
                        </a>
                        <a href="{% url 'events:detail' event.id %}" class="btn btn-info">{% trans "Volver al evento" %}</a>
                    </span>
                </h2>
                <h4>Lista de inscriptos al evento <strong><i>{{ event.name }}</i></strong></h4>
            </div>

            {% for participant in participants %}
                {% if forloop.first %}
                    <div class="row hidden-sm hidden-xs">
                        <div class="col-md-12">
                            <p>Los participantes <strong>Verificados</strong> son aquellos que:</p>
                            <ul>
                                <li>tienen login en PyAr o</li>
                                <li>inscriptos que verificaron su email siguiendo el link que les fue enviado.</li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered table-condensed">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>{% trans 'Nombre' %}</th>
                                            <th>{% trans 'Email' %}</th>
                                            <th>{% trans 'Género' %}</th>
                                            <th>{% trans 'Nivel' %}</th>
                                            <th>{% trans 'Usuario PyAr' %}</th>
                                            <th><small>{% trans 'Verificado?' %}</small></th>
                                            {% if event.has_sponsors %}
                                                <th>{% trans 'CV' %}</th>
                                                <th><small>{% trans 'Comparte?' %}</small></th>
                                            {% endif %}
                                            <th>{% trans 'Acciones' %}</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                {% endif %}

                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ participant.name }}</td>
                    <td>{{ participant.email|urlizetrunc:27 }}</td>
                    <td>{{ participant.gender|capfirst }}</td>
                    <td>{{ participant.seniority|capfirst }}</td>
                    <td>{{ participant.user|default_if_none:"" }}</td>
                    <td>
                        {% with participant.is_verified as v %}
                            {{ v|yesno:"Si,No" }}
                            <span
                                class="glyphicon glyphicon-{{ v|yesno:"ok,remove" }} text-{{ v|yesno:"success,warning" }}"
                                aria-hidden="true">
                            </span>
                        {% endwith %}
                    </td>

                    {% if event.has_sponsors %}
                        <td>{{ participant.cv|urlizetrunc:27 }}</td>
                        <td>
                        {% with participant.share_with_sponsors as s %}
                            {{ s|yesno:"Si,No" }}
                            <span
                                class="glyphicon glyphicon-{{ s|yesno:"ok,remove" }} text-{{ s|yesno:"success,warning" }}"
                                aria-hidden="true">
                            </span>
                        {% endwith %}
                        </td>
                    {% endif %}
                    <td>
                        <div class="btn-group btn-group-xs" role="group" aria-label="">
                            <a href="{% url 'events:unregister' participant.event.id participant.id %}" class="btn btn-danger">
                                <span
                                    class="glyphicon glyphicon-remove-sign"
                                    aria-hidden="true">
                                </span>
                                {% trans 'Eliminar' %}
                            </a>
                        </div>
                    </td>
                </tr>

                {% if forloop.last %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                {% endif %}

            {% empty %}

                <p class="list-group-item-text">{% trans "No hay inscriptos" %}</p>

            {% endfor %}
        </section>
</main>
{% endblock %}

templates/events/next_events.html
{% for event in events %}
    <article class="list-group-item">
      <h4 class="list-group-item-heading">
        <a href="{% url 'events:detail' event.id %}">
          {{ event.name }}
        </a>
      </h4>
      
      <p class="list-group-item-text">
        <span>{{ event.start_at|date:"DATE_FORMAT" }}</span> | 
        <span>{{ event.start_at|time:"TIME_FORMAT" }}</span> | 
        <span>{{ event.place }}</span>
      </p>
    </article>

{% empty %}
  <article class="list-group-item">
    <p class="list-group-item-text">No hay eventos a futuro</p>
  </article>
{% endfor %}